### ISSUE TITLE
Add Description Meta Tags to All Pages

### ISSUE THREAD

**Issue by BigSteveLittle** [RedAndBlackZone/redandblackzone#21]
This website was originally delivered as part of Certificate IV in Website Technologies that was completed in June 2021. Since then I have gone on to complete a Diploma in Website Development in December 2021.

So there are two main issues with the current site as outlined in the README.md file:

1. Major additions and re-development.
2. General fixes.

This fix is to add a meta tag **description** to all pages.

### Add Description Meta Tags to All Pages

- [ ] Create description for each page.
    - [ ] about 
        - [ ] SERVICES 
        - [ ] RESUME 
        - [ ] STEVE’S STORY 
        - [ ] CONTACTS 
    - [ ] portfolio 
        - [ ] WEB & DESIGN 
            - [ ] FRONT END DESIGN
            - [ ] CMS DEVELOPMENT
            - [ ] DATABASE DESIGN
            - [ ] GRAPHIC DESIGN
        - [ ] FILM & DIGITAL 
            - [ ] FILM PRODUCTION
            - [ ] EDITING
            - [ ] SCREENWRITING
            - [ ] PHOTOGRAPHY
    - [ ] my thoughts 
        - [ ] B-ROLL BLOG
- [ ] Add description to each page.
    - [ ] about 
        - [ ] SERVICES 
        - [ ] RESUME 
        - [ ] STEVE’S STORY 
        - [ ] CONTACTS 
    - [ ] portfolio 
        - [ ] WEB & DESIGN 
            - [ ] FRONT END DESIGN
            - [ ] CMS DEVELOPMENT
            - [ ] DATABASE DESIGN
            - [ ] GRAPHIC DESIGN
        - [ ] FILM & DIGITAL 
            - [ ] FILM PRODUCTION
            - [ ] EDITING
            - [ ] SCREENWRITING
            - [ ] PHOTOGRAPHY
    - [ ] my thoughts 
        - [ ] B-ROLL BLOG
- [ ] Final Check and Testing.
